#!/bin/sh
cd "$(dirname "$0")" || exit 255
if test x"$(cat .symlink.tst 2>&1)" = x"meow"; then
	test x"$1" = x"/q" || echo >&2 This git repository seems to have \
	    been cloned with symlinks enabled, ok.
	exit 0
fi
echo >&2 '
==================================================
THIS GIT REPOSITORY IS *NOT* CHECKED OUT CORRECTLY
==================================================

It MUST be cloned with symbolic links ENABLED.

Check https://stackoverflow.com/a/49913019/2171120 for
information on how to do that (including using gpedit
as https://www.joshkel.com/2018/01/18/symlinks-in-windows/
describes, or setting Windows 10 (1703 or newer) to
Developer Mode). Then, erase this directory and clone
it again (then run this script again to verify it's right).'
exit 1
